"""Programs and Pricelist management

Revision ID: 37fbee4e84d9
Revises: bdbc7e84b071
Create Date: 2024-08-23 16:31:07.668451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '37fbee4e84d9'
down_revision: Union[str, None] = 'bdbc7e84b071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted by ameni! ###
    op.create_table('pricelist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricelist_id'), 'pricelist', ['id'], unique=False)
    op.create_table('pricelistLine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('new_price', sa.Float(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('pricelist_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('start_date <= end_date', name='check_start_end_date'),
    sa.ForeignKeyConstraint(['pricelist_id'], ['pricelist.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricelistLine_id'), 'pricelistLine', ['id'], unique=False)
    op.create_table('program',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('program_type', sa.Enum('discount', 'get_x_buy_y', name='programtype'), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('product_buy_id', sa.Integer(), nullable=True),
    sa.Column('product_get_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_buy_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_get_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_program_id'), 'program', ['id'], unique=False)
    op.create_table('program_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('code_status', sa.Enum('active', 'inactive', name='codestatus'), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_program_item_id'), 'program_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted by ameni! ###
    op.drop_index(op.f('ix_program_item_id'), table_name='program_item')
    op.drop_table('program_item')
    op.drop_index(op.f('ix_program_id'), table_name='program')
    op.drop_table('program')
    op.drop_index(op.f('ix_pricelistLine_id'), table_name='pricelistLine')
    op.drop_table('pricelistLine')
    op.drop_index(op.f('ix_pricelist_id'), table_name='pricelist')
    op.drop_table('pricelist')
    # ### end Alembic commands ###
